USER_DATA = {
    "admin": {
        "password": "password123",
        "secret_key": "FLAG{SSTI_PWNED}",
        "avatar": "user_1001.png",
        "email": "admin@example.com",
        "phone": "+84123456789",
        "address": "123 Đường ABC, Quận 1, TP. HCM",
        "job": "Kỹ sư phần mềm",
        "dob": "1995-06-20",
        "hobbies": ["Đọc sách", "Lập trình", "Chơi CTF", "<b style=color=red>FLAG{I_L1k3_DCT_St3go}</b>"],
        "is_active_backup": True,
        "secret_key": "32*ZG4ISY0jYx8qeZVr0rT8tigJpVzgXc6i",
    },
    "bob": {
        "password": "securepass",
        "secret_key": "SECRET_1234",
        "avatar": "user_1002.png",
        "email": "bob@example.com",
        "phone": "+84987654321",
        "address": "456 Đường XYZ, Quận 3, Hà Nội",
        "job": "Chuyên gia an ninh mạng",
        "dob": "1990-11-15",
        "hobbies": ["Bóng đá", "Hackathon", "Chạy bộ"],
        "is_active_backup": False,
        "secret_key": "",
    },
    "charlie": {
        "password": "charliepass",
        "secret_key": "HIDDEN_FLAG_5678",
        "avatar": "user_1003.png",
        "email": "charlie@example.com",
        "phone": "+84333444555",
        "address": "789 Đường DEF, Quận 2, Đà Nẵng",
        "job": "Nhà nghiên cứu AI",
        "dob": "1998-03-10",
        "hobbies": ["Chơi game", "Học AI", "Nấu ăn"],
        "is_active_backup": False,
        "secret_key": "",
    }
}
